[42기 성은정] Nav 페이지 레이아웃
wecode-bootcamp-korea/42-1st-Naweki-frontend pull request #2
Opened 2023-02-07 11:39 UTC by eejungee

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 레이아웃
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 마우스 오버 시 해당 메뉴를 보여주는 nav 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. nav 레이아웃 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- css와 친해지고 있습니다

<br />

## :: 기타 질문 및 특이 사항
- menulist에 mouseenter 시 하단에 나오는 menubox는 데이터와 css 모두 수정 중입니다

2023-02-10 07:32 UTC, hani2525 requested changes
은정님! 리뷰 확인하신 후 반영해주세요!

2023-02-10 07:32 UTC, hani2525 commented on src/components/Nav/MenuBox/MenuBox.js
> +          </div>
해당 부분은 코드도 중복되는 부분도 많고 UI도 분리할 수 있을 것 같아 컴포넌트화 시키면 좋을 것 같네요!
컴포넌트화 시켜서 반복문을 통해 UI를 효과적으로 관리하는 방법을 익혀봅시다.

2023-02-10 07:32 UTC, hani2525 commented on src/components/Nav/MenuBox/MenuBox.js
> +      {isShown ? (
굳이 삼항연산자로 true, false 케이스 모두 처리하여 null을 반환할 필요없이 이 부분은 true 케이스만 처리하면 되기 때문에 조건부 렌더링 (`&&` 연산자)을 활용하면 불필요한 코드를 없애 더욱 가독성에 좋아집니다. 

- 참고 : 공식문서 조건부 렌더링([https://ko.reactjs.org/docs/conditional-rendering.html](https://ko.reactjs.org/docs/conditional-rendering.html))

```jsx
true ? foo : null => true && foo // true인 경우에 foo 요소를 렌더
```

2023-02-10 07:32 UTC, hani2525 commented on src/components/Nav/Nav.js
> +      return !prev;
함수 내부의 내용이 반환값(return)만 있다면 중괄호({}) 와 return 을 생략할 수 있습니다.

2023-02-10 07:32 UTC, hani2525 commented on src/components/Nav/Nav.js
> +        <>
false일 때 보여주는 부분 코드가 굉장히 긴데 이 부분은 컴포넌트화 하는 건 어떨까요?

2023-02-10 07:32 UTC, hani2525 commented on src/components/Nav/Search/Search.js
> +  console.log(keyword);
- 테스트나 디버깅용으로 쓰는 로그가 계속해서 코드에 남아있을 경우 가독성에 좋지 않습니다.
- 다른 개발자로 하여금 혼란을 줄 수 있고, 가독성에 좋지 않으므로 테스트 마친 `console.log`  는 모두 삭제해주세요

2023-02-12 07:41 UTC, eejungee commented on src/components/Nav/MenuBox/MenuBox.js
> +      {isShown ? (
앗 제가 그전에 &만 썼다가 안돼서 일단 삼항연산자로 처리했었는데 &&이었군요,,, 수정했습니다!!

2023-02-13 09:31 UTC, eejungee commented on src/components/Nav/Menu/Menu.js
> +              )} */}
현재는 주석처리하지 않고 사용하고 있습니다~~
fileChanged 탭에서 확인 부탁드려요
여기에서는 왜 자동으로 반영되지 않는지 모르겠습니다,,,

2023-02-13 09:32 UTC, eejungee commented on src/components/Nav/Search/Search.js
> +  }, [keyword]);
넵 fetch로 수정했습니다

2023-02-14 00:46 UTC, hani2525 approved these changes

2023-02-14 00:49 UTC, merged