[42기 이유진] Add: Main Page Layout
wecode-bootcamp-korea/42-1st-Naweki-frontend pull request #4
Opened 2023-02-08 05:32 UTC by yujinni

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
메인 페이지 레이아웃 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
메인 페이지 레이아웃 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
페이지 내 영상 삽입 방법 및 오류 해결 방법을 학습하였습니다.

<br />

2023-02-09 09:57 UTC, yujinni commented on src/pages/Main/Main.js
> +  const [featuredShoes, setFeaturedShoes] = useState([]);
나이키 홈페이지 Featured Shoes 카테고리와 동일하게 작성하였는데 Recommend Items로 변경 예정입니다. 수정에 참고하겠습니다!

2023-02-09 09:58 UTC, yujinni commented on src/pages/Main/Main.js
> +      <button className="jordanParisBuyBtn" type="button">
메인 페이지 제품은 레이아웃 내 이미지 그대로 사용할 예정입니다. (하단 추천 상품 슬라이드 제외) 
네이밍 시 확장성 고려하도록 하겠습니다!

2023-02-09 10:17 UTC, yujinni commented on src/pages/Main/FeaturedShoes/FeaturedShoes.js
> +    <div className="featuredShoesBox">
수정했습니다!

2023-02-09 10:17 UTC, yujinni commented on src/pages/Main/Main.js
> +  const [featuredShoes, setFeaturedShoes] = useState([]);
수정했습니다.

2023-02-10 07:52 UTC, hani2525 requested changes
Main 컴포넌트의 코드 길이가 꽤 긴데, 레이아웃별로 컴포넌트로 만들어서 Main 컴포넌트를 재구성해보세요!

2023-02-10 07:52 UTC, hani2525 commented on src/pages/Main/Main.js
> +      </div>
해당 코드는 많이 중복되네요!
안에 있는 데이터는 상수데이터로 관리하시고
반복문을 통해 UI를 관리하시면 더 깔끔하게 코드를 작성할 수 있겠죠?
이번 기회에 한 번 연습해보시면 좋을 것 같습니다.

2023-02-10 07:52 UTC, hani2525 commented on src/pages/Main/Main.js
> +        </button>
button이 많이 사용된다면 컴포넌트로 만들어서 관리하면 더 효율적이겠죠?

2023-02-10 07:52 UTC, hani2525 commented on src/pages/Main/Main.js
> +      </button>
구매하기 button 을 만들 때 type을 submit, button 다 다르게 부여하셨는데 이유가 뭘까요~?

2023-02-10 07:52 UTC, hani2525 commented on src/pages/Main/Main.scss
> +    margin-bottom: 20px;
- margin, padding에 속성을 부여할 경우 상황에 따라서 shorthand property를 이용해서 손쉽게 부여할 수 있습니다.
    
    ```css
    //예시
    margin-top: 20px;
    margin-right: 0;
    margin-bottom: 10px;
    margin-left: 0;
    
    // shorthand property
    margin: 20px 0 10px;
    ```

2023-02-10 07:52 UTC, hani2525 commented on src/pages/ProductDetail/ProductDetail.scss
> +    // border: 1px solid red;
콘솔은 지워주세요~

2023-02-14 00:47 UTC, hani2525 approved these changes

2023-02-14 10:53 UTC, closed without merging